### PR TITLE
fix: explict mark check button

### PR DESCRIPTION
**Pull request by hunjixin**
this button show checkbox in kde, but show common button in ubunut. just make common button work the same

### CODE REVIEW

**Comment by sidit77** [comment]
This seems to be a duplicate of #1, which seems to be abandoned. 

Like I said in the other PR, I would prefer to change the type of checked to `Option<bool>` instead. This also makes fixing the Windows and MacOS backends easier as you'd just have to do a `checked.unwrap_or_default()`.

**Comment by hunjixin** [comment]
@sidit77  i can have try for linux and win， Please take a look at the code, and see if it's the same as what you mentioned.

**Comment by sidit77** [comment]
Everything seems good to me now.

Just FYI: 
You should still be able to use `cargo check --target x86_64-apple-darwin` to check the mac version from linux/windows. Just make sure to install the `x86_64-apple-darwin` toolchain.
I generally use this to make sure I don't accidentally break a platform:
```
cargo check --all-features --target x86_64-pc-windows-msvc
cargo check --all-features --target x86_64-unknown-linux-gnu
cargo check --all-features --target x86_64-apple-darwin
```

**Comment by nazar-pc** [comment]
Could you publish a new release with this change, please?

**Comment by flukejones** [comment]
Thanks for getting this done! Also apologies for not finishing the last PR. I got snowed under with too many tasks.

**Pull request merged**
